from __future__ import annotations
from .types import MetricSpec
import config  # 절대 임포트

REGISTRY={
    'A2_001': {'id':'A2_001','name':'상품별매출순위','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_001','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_002': {'id':'A2_002','name':'상품별주문수순위','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_002','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_003': {'id':'A2_003','name':'히트상품기여도','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_003','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_004': {'id':'A2_004','name':'상품별취소율','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_004','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_005': {'id':'A2_005','name':'상품별반품율','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_005','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_006': {'id':'A2_006','name':'상품매출성장률','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_006','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_007': {'id':'A2_007','name':'상품매출순위변동','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_007','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_008': {'id':'A2_008','name':'상품가격대별매출분포','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_008','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_009': {'id':'A2_009','name':'상품별클레임율','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_009','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A2_010': {'id':'A2_010','name':'상품별재구매기여도','area':2,'description':'자동생성','func_fqn':'metrics.area2_product.mA2_010','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_001': {'id':'A4_001','name':'업체별총매출액','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_001','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_002': {'id':'A4_002','name':'업체별총주문수','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_002','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_003': {'id':'A4_003','name':'업체별평균주문금액','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_003','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_004': {'id':'A4_004','name':'업체별총수익액','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_004','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_005': {'id':'A4_005','name':'업체별총수량','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_005','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_006': {'id':'A4_006','name':'업체별매출순위','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_006','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_007': {'id':'A4_007','name':'업체별매출성장률(전기대비)','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_007','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_008': {'id':'A4_008','name':'업체매출성장률','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_008','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_009': {'id':'A4_009','name':'업체별매출순위변동','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_009','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_010': {'id':'A4_010','name':'업체별평균마진율','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_010','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_011': {'id':'A4_011','name':'업체별마진순위','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_011','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_012': {'id':'A4_012','name':'업체별취소율','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_012','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_013': {'id':'A4_013','name':'업체별반품율','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_013','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_014': {'id':'A4_014','name':'업체별교환율','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_014','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A4_015': {'id':'A4_015','name':'업체별클레임율','area':4,'description':'자동생성','func_fqn':'metrics.area4_order_status.mA4_015','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_001': {'id':'A3_001','name':'총고객수','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_001','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_002': {'id':'A3_002','name':'재구매율','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_002','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_003': {'id':'A3_003','name':'상위10퍼고객매출비중','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_003','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_004': {'id':'A3_004','name':'다중구매고객비율','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_004','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_005': {'id':'A3_005','name':'고객당평균구매상품수','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_005','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_006': {'id':'A3_006','name':'신규고객비율','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_006','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_007': {'id':'A3_007','name':'기존고객이탈률','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_007','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_008': {'id':'A3_008','name':'재구매고객매출비중','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_008','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_009': {'id':'A3_009','name':'고객재구매횟수분포','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_009','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A3_010': {'id':'A3_010','name':'고객평균LTV','area':3,'description':'자동생성','func_fqn':'metrics.area3_customer.mA3_010','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_001': {'id':'A1_001','name':'채널별매출비중','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_001','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_002': {'id':'A1_002','name':'채널별주문수비중','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_002','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_003': {'id':'A1_003','name':'채널별업체매출순위','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_003','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_004': {'id':'A1_004','name':'채널별업체점유율','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_004','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_005': {'id':'A1_005','name':'채널매출성장률','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_005','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_006': {'id':'A1_006','name':'채널주문수성장률','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_006','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_007': {'id':'A1_007','name':'채널점유율추세','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_007','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_008': {'id':'A1_008','name':'채널별매출순위변동','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_008','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_009': {'id':'A1_009','name':'채널내업체매출순위변동','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_009','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_010': {'id':'A1_010','name':'채널내상품매출순위','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_010','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_011': {'id':'A1_011','name':'채널별취소율','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_011','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_012': {'id':'A1_012','name':'채널별반품율','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_012','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_013': {'id':'A1_013','name':'채널별클레임율','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_013','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A1_014': {'id':'A1_014','name':'채널딜기여도','area':1,'description':'자동생성','func_fqn':'metrics.area1_channel.mA1_014','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_001': {'id':'A5_001','name':'카테고리중분류별매출','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_001','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_002': {'id':'A5_002','name':'카테고리중분류별업체매출순위','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_002','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_003': {'id':'A5_003','name':'카테고리중분류별상품매출순위','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_003','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_004': {'id':'A5_004','name':'카테고리중분류별업체시장점유율','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_004','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_005': {'id':'A5_005','name':'카테고리중분류별주문수','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_005','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_006': {'id':'A5_006','name':'카테고리중분류별평균주문금액','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_006','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_007': {'id':'A5_007','name':'카테고리중분류별매출순위변동','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_007','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_008': {'id':'A5_008','name':'카테고리중분류별점유율','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_008','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_009': {'id':'A5_009','name':'카테고리중분류별점유율추세','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_009','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_010': {'id':'A5_010','name':'카테고리중분류Top5','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_010','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_011': {'id':'A5_011','name':'카테고리중분류Top5성장률','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_011','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_012': {'id':'A5_012','name':'카테고리소분류별매출','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_012','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_013': {'id':'A5_013','name':'카테고리소분류별업체매출순위','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_013','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_014': {'id':'A5_014','name':'카테고리소분류별상품매출순위','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_014','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_015': {'id':'A5_015','name':'카테고리소분류별업체시장점유율','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_015','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_016': {'id':'A5_016','name':'카테고리소분류별주문수','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_016','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_017': {'id':'A5_017','name':'카테고리소분류별평균주문금액','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_017','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_018': {'id':'A5_018','name':'카테고리소분류별매출순위변동','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_018','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_019': {'id':'A5_019','name':'카테고리소분류별점유율','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_019','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_020': {'id':'A5_020','name':'카테고리소분류별점유율추세','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_020','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_021': {'id':'A5_021','name':'카테고리소분류Top5','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_021','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A5_022': {'id':'A5_022','name':'카테고리소분류Top5성장률','area':5,'description':'자동생성','func_fqn':'metrics.area5_category.mA5_022','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_001': {'id':'A6_001','name':'트렌드일자별매출추이','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_001','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_002': {'id':'A6_002','name':'트렌드일자별주문수추이','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_002','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_003': {'id':'A6_003','name':'트렌드주차별매출추이','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_003','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_004': {'id':'A6_004','name':'트렌드매출성장률2주','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_004','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_005': {'id':'A6_005','name':'트렌드시간대별매출패턴','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_005','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_006': {'id':'A6_006','name':'트렌드시간대별주문수패턴','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_006','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_007': {'id':'A6_007','name':'트렌드피크시간대Top3','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_007','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_008': {'id':'A6_008','name':'트렌드요일별매출패턴','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_008','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_009': {'id':'A6_009','name':'트렌드요일패턴스코어','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_009','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_010': {'id':'A6_010','name':'트렌드채널별매출추이','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_010','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
    'A6_011': {'id':'A6_011','name':'트렌드중분류별매출추이Top5','area':6,'description':'자동생성','func_fqn':'metrics.area6_trend.mA6_011','input_contract':{},'output_schema':[],'default_params':config.DEFAULT_PARAMS},
}
def build_registry(): return REGISTRY
def get_metric_spec(metric_id: str) -> MetricSpec: return REGISTRY[metric_id]
def list_metrics(area: int | None=None, q: str | None=None):
    items = list(REGISTRY.values())
    if area is not None: items = [x for x in items if x['area']==area]
    if q:
        ql = q.lower()
        items = [x for x in items if ql in x['name'].lower() or ql in x['id'].lower()]
    items.sort(key=lambda x: (x['area'], x['id']))
    return items
